project:
  type: website
  resources:
    - audio
    - assets/data
  render:
    - "*.qmd"
    - "report/*.qmd"
    - "technical-details/**/*.qmd"
    - "technical-details/**/*.ipynb"
    - "logs/*.qmd"
    - "!xtra"

website:
  title: "Distance Doesn't Explain Price"
  favicon: "assets/logo.png"
  navbar:
    left:
      - href: report/report.qmd
        text: Report
      - href: report/about.qmd
        text: About Us
      - text: "Technical Details"
        menu:
          - text: Data Cleaning
            href: technical-details/data-cleaning/dataclean.ipynb
          - text: Exploratory Data Analysis
            href: technical-details/eda/data_exploration.ipynb
          - text: Linked View (Norman)
            href: technical-details/story/interactive_viz_2.ipynb
          - text: Static Visualization 1
            href: technical-details/story/static_viz_1.ipynb
          - text: Linear Regression
            href: technical-details/story/linear_reg.ipynb
          - text: T-Test
            href: technical-details/story/t_test.ipynb
          - text: "---"
          - text: Technical Appendix
            href: technical-details/appendix.qmd
          - text: Progress Log
            href: logs/progress-log.qmd
          - text: LLM Usage Log
            href: logs/llm-usage-log.qmd

format:
  html:
    theme: yeti
    toc: true
